### ISSUE TITLE
フォームから想定していない値が送信される

### ISSUE THREAD

**Issue by YamashitaRintaro** [YamashitaRintaro/prep_method_training#30]
## 実現したいこと

1. /trainings/new_graduateを開く
2. 質問を選択し、送信
3. 質問のid(question_id)と質問のタイトル(question.title)、current_user.idをもとにtraining作成

## 現状発生している問題・エラーメッセージ
training作成フォームから想定していない値が送信されるバグが発生しています。
trainingは選択した質問のidとtitle、current_user.idを元に作成されます。
選択した質問のidは正しいのですが、別の質問のtitleが保存されます。
trainingsテーブルのtitleカラムには、デフォルトで親テーブル(questionテーブルのtitleカラム)が登録される仕様です。

### ER図
![ポートフォリオ-userにカテゴリー drawio](https://user-images.githubusercontent.com/80795057/160220542-a27040a0-50a8-4623-9e08-8bba4d22dd0f.png)

### training作成フォーム
```
  <%= form_with model: @training, url: trainings_path, local: true do |f| %>
    <div class="w-75 mx-auto">
      <ul class="list-group">
        <li class = "list-header font">質問リスト</li>
        <% @questions.each do |question| %>
          <li class="list-group-item font">
            <%= f.radio_button :question_id, question.id %>
            <%= f.label :queston_id, question.title, value: question.id %>
            <%= f.hidden_field :title, value: question.title %>  #ここ
          </li>
        <% end %>
      </ul>
      <div class="text-center">
        <%= f.submit '次へ', class: 'btn btn-lg bg text-white w-25 mt-5' %>
      </div>
    </div>
  <% end %>
```
### trainings_controller.rb 
```
class TrainingsController < ApplicationController
  
  def create
    @training = current_user.trainings.new(training_params)
    if @training.save
      redirect_to training_path(@training)
    else
      flash.now[:danger] = '質問を選択してください'
      redirect_back fallback_location: root_path
    end
  end

  def destroy
    @training = current_user.trainings.find(params[:id])
    @training.destroy!
    redirect_back fallback_location: root_path
  end
  
  def new_graduate
    @questions = Question.where(category_id: 1)
    @training = Training.new
  end
  
  def job_change
    @questions = Question.where(category_id: 2)
    @training = Training.new
  end
  
  def engineer
    @questions = Question.where(category_id: 3)
    @training = Training.new
  end

  def show
    @training = current_user.trainings.find(params[:id])
    @question = @training.question
    @question_title = @training.question.title
    @question_voice_data = @training.question.question_voice_data
  end
  
  private
  
  def training_params
    params.require(:training).permit(:user_id, :question_id, :title)
  end
end
```
question_id: 1の質問（自己紹介をしてください）を選択し、trainingを作成したところ、question_idは正しいにも関わらず、question_id: 7のタイトル（学生時代に頑張ったことを教えてください）が保存されます。

<img width="853" alt="スクリーンショット 2022-03-25 17 09 36" src="https://user-images.githubusercontent.com/80795057/160080560-c116be35-97ad-443d-845f-cafb02c7dee9.png">

### ターミナル
```
Started POST "/trainings" for ::1 at 2022-03-26 10:46:32 +0900
Processing by TrainingsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "training"=>{"question_id"=>"1", "title"=>"学生時代に頑張ったことを教えてください"}, "commit"=>"次へ"}
  User Load (3.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  TRANSACTION (0.9ms)  BEGIN
  ↳ app/controllers/trainings_controller.rb:5:in `create'
  Question Load (2.4ms)  SELECT "questions".* FROM "questions" WHERE "questions"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  ↳ app/controllers/trainings_controller.rb:5:in `create'
  Training Create (3.8ms)  INSERT INTO "trainings" ("user_id", "question_id", "title", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["user_id", 1], ["question_id", 1], ["title", "学生時代に頑張ったことを教えてください"], ["created_at", "2022-03-26 10:46:32.784838"], ["updated_at", "2022-03-26 10:46:32.784838"]]
  ↳ app/controllers/trainings_controller.rb:5:in `create'
  TRANSACTION (3.7ms)  COMMIT
  ↳ app/controllers/trainings_controller.rb:5:in `create'
Redirected to http://localhost:3000/trainings/48
Completed 302 Found in 62ms (ActiveRecord: 28.1ms | Allocations: 9285)
```

**Comment by YamashitaRintaro** [comment]
HTMLを確認したところ、hidden_field（タイトル）には問題なく親のタイトルが入っている。
<img width="554" alt="スクリーンショット 2022-03-25 20 03 24" src="https://user-images.githubusercontent.com/80795057/160109938-ba674b72-e212-4528-8bb4-198a855f6e06.png">

```
<%= f.label :queston_id, question.title, value: question.id %>
<%= f.hidden_field :title, value: question.title %>
```
labelの `question.title`と、hidden_fieldの `question.title`の出力が違う理由が不明。

**Comment by murata0705** [comment]
question_id は radio button になっているので、選択した id が `training[question_id]` に設定され、

```ruby
def training_params
    params.require(:training).permit(:user_id, :question_id, :title)
  end
```

で取得できますが、title は、単に hidden_field で設定されているだけなので、`training[title]`の値が、上から順番に上書きされていき、一番最後の question_id = 7 の値が設定されているのだと思われます。例えば、question_id = 6 の HTML を一番下に移動すると、「志望動機を教えてください」が設定されると思います。

title もラジオボタンで設定するか、id を選択すると、title も動的に設定されるよう、js を書く必要があると思います。

**Comment by YamashitaRintaro** [comment]
ご回答ありがとうございます！
おっしゃる通り、title もラジオボタンで設定すると解決しました。
見た目の問題でjsを書こうと思います。
ありがとうございました！
